import React from 'react';
import mapModifiers from 'utils/functions';

export type IconName =
  'history2' |
  'fast_delivery' |
  'giftbox' |
  'sending' |
  'histories_call' |
  'chevron-up' |
  'histories_call-yellow' |
  'balancer' |
  'balancer-yellow' |
  'filter_chat' |
  'compare_crm' |
  'detail_crm' |
  'download_crm' |
  'summary_crm' |
  'origin-white' |
  'networking' |
  'exchange' |
  'list_text' |
  'report_crm2' |
  'report_crm2-yellow' |
  'to' |
  'health-insurance' |
  'dial' |
  'merge' |
  'emergency' |
  'call_out' |
  'call_in' |
  'call_fail' |
  'dial-pad' |
  'history' |
  'menu_fold' |
  'menu_unfold' |
  'folder' |
  'portrait' |
  'faqs' |
  'task' |
  'recent_result' |
  'results' |
  'interactive' |
  'price-list' |
  'exits' |
  'phone_hangup' |
  'phone_accept' |
  'check-list' |
  'setting_crm-white' |
  'chevron-bottom' |
  'setting-lines' |
  'left-arrow' |
  'attachment' |
  'arrow_down' |
  'picture' |
  'video' |
  'template_message' |
  'check' |
  'has_phone_channel' |
  'comment_channel' |
  'messages_channel' |
  'get_otp' |
  'pencil' |
  'clean_filter' |
  'addV2' |
  'statistics_white' |
  'close_drawer' |
  'list_exam' |
  'list_exam-yellow' |
  'woman' |
  'reload' |
  'men' |
  'book' |
  'upload' |
  'analysis' |
  'search' |
  'dropDown' |
  'bell' |
  'Earth' |
  'home' |
  'user' |
  'VietNam' |
  'close' |
  'close_v2' |
  'errorOutline' |
  'successOutline' |
  'add' |
  'Korean' |
  'England' |
  'cancel' |
  'chevronLeft' |
  'chevronRight' |
  'hamburger' |
  'dropDown_blue' |
  'clock' |
  'calendar' |
  'doneall' |
  'right' |
  'left_feild' |
  'addInput' |
  'calendar_white' |
  'setting' |
  'tag' |
  'message' |
  'showpass' |
  'hidepass' |
  'logout' |
  'timezone' |
  'drop_up' |
  'loading_notify' |
  'loading_crm' |
  'done_notify' |
  'circle_half' |
  'confirm' |
  'cancelimage' |
  'edit' |
  'cancel_notify' |
  'task_notify' |
  'department_list' |
  'edit_dept' |
  'delete_item' |
  'save_all' |
  'right_feild' |
  'dept_mail' |
  'dept_info' |
  'dept_phone' |
  'file' |
  'micro' |
  'sidebar_menu' |
  'addgroup' |
  'download' |
  'playVoice' |
  'darkmode' |
  'lightmode' |
  'pauseVoice' |
  'ticket_crm' |
  'channel_crm' |
  'marketing_crm' |
  'dashboard_crm' |
  'person_crm' |
  'report_crm' |
  'setting_crm' |
  'delete_crm' |
  'edit_info' |
  'facebook' |
  'tags_crm' |
  'accept_crm' |
  'add_crm' |
  'excel' |
  'animal1' |
  'animal2' |
  'animal3' |
  'animal4' |
  'animal5' |
  'facebook_channel' |
  'zalo_channel' |
  'show_sidebar' |
  'call' |
  'call_blue' |
  'video_call' |
  'emoji_smile' |
  'grid_fill' |
  'folder_fill' |
  'send' |
  'reset' |
  'chat_crm' |
  'play' |
  'play2' |
  'pause' |
  'question' |
  'question_white' |
  'add_crm_v2' |
  'backspace' |
  'hide_popup' |
  'fullscreen' |
  'plus' |
  'delay' |
  'destroy' |
  'link' |
  'telephone' |
  'hangup' |
  'accept_call' |
  'dialpad' |
  'pause_phone' |
  'note_phone' |
  'transfer' |
  'unmute' |
  'mute' |
  'recording' |
  'unrecording' |
  'user_management' |
  'user_management_off' |
  'add-booking' |
  'download_blue' |
  'messenger' |
  'phone_icon' |
  'phone_icon-main' |
  'filter' |
  'search_white' |
  'continue' |
  'burger_white' |
  'close_white' |
  'burger_white_hover' |
  'edit_crm' |
  'messager_crm' |
  'note_crm' |
  'hook_tag' |
  'add_tag' |
  'done_circle' |
  'close_circle' |
  'done_tag' |
  'accept_crm_feild' |
  'list_note' |
  'list_schedule' |
  'before_exams' |
  'after_exams' |
  'misscall_crm' |
  'conversion' |
  'list_appointment' |
  'after_exams-yellow' |
  'before_exams-yellow' |
  'list_appointment-yellow' |
  'list_schedule-yellow' |
  'report_crm-yellow' |
  'setting_crm-yellow' |
  'ticket_crm-yellow' |
  'misscall_crm-yellow' |
  'marketing_crm-yellow' |
  'person_crm-yellow' |
  'canceled_crm' |
  'criminal-record' |
  'delay_crm' |
  'pdf' |
  'effect' |
  'stats' |
  'visualization' |
  'chat_crm-yellow' |
  'conversion-white' |
  'conversion-yellow' |
  'list_appointment-white' |
  'before_exams-white' |
  'misscall_crm-white' |
  'chat_crm-white' |
  'back' |
  'send-message' |
  'chevron-down';
export type IconSize = '6x12' | '8x12' | '10x10' | '14x14' | '16x16' | '17x17' | '18x18' | '20x20' | '20x15' | '24x24' | '28x28' | '32x32' | '40x40' | '80x80' | '5x10' | '69x72' | '34x34' | '30x30' | '12x12' | '25x27' | '25x25' | '17x12' | '21x21' | '25x19' | '36x36' | '22x16' | '26x26' | '44x44' | '120x120' | '17x19';

interface IconProps {
  iconName: IconName;
  size?: IconSize;
  isPointer?: boolean;
  style?: React.CSSProperties;
  onClick?: () => void;
}

const Icon: React.FC<IconProps> = ({
  iconName, size, isPointer, style, onClick
}) => (
  <i className={mapModifiers('a-icon', iconName, size, isPointer && 'pointer')} style={style} onClick={onClick} />
);

Icon.defaultProps = {
  size: '24x24',
};

export default React.memo(Icon);
